plugins {
    id "com.android.application"
}

android {
    namespace "cloud.watchtogethernow.mobile"
    compileSdk 36
    buildToolsVersion "36.0.0"

    defaultConfig {
        applicationId "cloud.watchtogethernow.mobile"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "0.1.0"

        buildConfigField "String", "SERVER_ORIGIN", '"https://watchtogethernow.cloud"'
        buildConfigField "String", "LEGAL_NOTICE_VERSION", '"2026-07-28"'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}
